services:
  postgres:
    container_name: task_postgres
    image: postgres:13
    restart: "always"
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: task